version: "3.9"

services:
  motorx-app:
    image: kevinmitsi/motorx-backend:v1
    container_name: motorx-app
    restart: always

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-motorx}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: prod

    ports:
      - "${PORT:-8080}:8080"